DFA-1059 - Check if the user's email is all already registered with t…
alphagov/di-onboarding-self-service-experience pull request #149
Opened 2022-10-16 21:58 UTC by HarshVasudev

- Check if the user's email is all already registered with 
- Code tidy up as per ESlint.

2022-10-17 11:01 UTC, JohnWattsGDS requested changes
We need feature tests for this flow.

You will need to alter the `StubCognitoClient`.  Line 122 in the `createUser` stub implementation should specify the method `createUser` instead of `login`; it looks like there was some copy and pasting that went wrong.

Once that's done then if the feature test tries to create and account with the email address `inuse@foo.gov.uk` the correct exception will be thrown to trigger this flow.  You can check the first entry in `stubs/stubs-config.json` to see how the `StubCongitoClient` knows to throw the error.

It should probably be a new `scenario` in `features/sign-up.feature` - the first five steps of most if not all scenarios should be copyable if you change the email and redirected-to values.  Also check that the email address is rendered on the page.

2022-10-17 13:34 UTC, HarshVasudev commented on express/src/controllers/create-account.ts
>              // TODO We need to handle this properly with another flow
Done.

2022-10-17 13:39 UTC, JohnWattsGDS commented on express/src/controllers/create-account.ts
>              // TODO We need to handle this properly with another flow
I don't think it's been added and committed.

2022-10-18 11:37 UTC, JohnWattsGDS commented on express/src/controllers/create-account.ts
> +    let result: AdminCreateUserCommandOutput;
😄 👍🏻

2022-10-18 12:10 UTC, JohnWattsGDS approved these changes
👍🏻

2022-10-18 12:12 UTC, merged