SSE-2647 - Update empty user attributes play back
alphagov/di-onboarding-self-service-experience pull request #315
Opened 2023-05-18 17:35 UTC by BorisP-GDS

Update empty user attributes play back

2023-05-19 09:07 UTC, JohnWattsGDS approved these changes

2023-05-19 15:09 UTC, CharlesIC requested changes
Need better checking to ensure we only exclude `openid`

2023-05-19 16:00 UTC, CharlesIC commented
Blocked on SSE-2652

2023-05-25 17:02 UTC, BorisP-GDS commented
Closing this PR as the story is abandoned. Changes no longer needed. SSE-2647

2023-05-25 17:02 UTC, closed without merging