SSE-2869   Review and Update WAF Rules for Load Balancer
alphagov/di-onboarding-self-service-experience pull request #446
Opened 2023-10-09 16:43 UTC by rafal-surowiec-co

2023-10-10 14:43 UTC, abdul-gds commented on infrastructure/frontend/frontend.template.yml
> +        Allow: {}
value required

2023-10-13 12:28 UTC, keith-hart requested changes
shouldn't lines 99-120 be changed now the policy character limit is changed

2023-10-13 12:29 UTC, MartinH-DI submitted a review, later dismissed
Looks good

2023-10-16 09:59 UTC, rafal-surowiec-co commented
> shouldn't lines 99-120 be changed now the policy character limit is changed

Addressed

2023-10-16 11:20 UTC, closed without merging